### ISSUE TITLE
A Restart Button

### ISSUE THREAD

**Issue by preshengr** [Gifftybabe/who-wants-to-be-a-millionaire-#1]
Hello Dear great work indeed you are exploring and its lovely.
I suggest you add a restart button on the play environment to enable players restart if they loose the game.
Also do you think it would be wise if you allowed gamers to see what they got wrong then shuffle the questions on start to create a little rigidity in the game.

"Please Let it be noted that this issue is not to defame the project but to improve it"

Thank you.

**Comment by Gifftybabe** [comment]
Thanks for the observation, I will sure implement it as soon as possible.
To reshuffle the questions will mean fetching data from an external source as the questions I provided are limited.

I sure will put all those into consideration.
Thank you again
